---
- name: Install td-agent
  import_tasks: install.yml
  become: true
  tags:
    - tdagent_install

- name: Configure barito agent
  import_tasks: config.yml
  become: true
  tags:
    - barito_agent_config

- name: Set service daemon
  service:
    name: td-agent
    state: started
    enabled: yes
