---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance_1804
    image: jrei/systemd-ubuntu:18.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: instance_1604
    image: jrei/systemd-ubuntu:16.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance_1604:
        tdagent_version: "3"
      instance_1804:
        tdagent_version: "4"
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
