---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: jrei/systemd-ubuntu:18.04
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
